# Generated by Django 2.2.12 on 2020-06-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200625_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_caption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='image',
        ),
    ]
